// Generated by CoffeeScript 1.10.0
var MyRegExp;

MyRegExp = (function() {
  function MyRegExp() {
    console.log("MyRegExp::constructor()");
    this._debug = true;
    return;
  }

  MyRegExp.prototype.isValid = function(regex) {
    if (this._debug) {
      console.log("MyRegExp::isValid");
    }
  };

  MyRegExp.prototype.test = function(text, regex) {
    if (this._debug) {
      console.log("MyRegExp::test");
    }
  };

  MyRegExp.prototype.exec = function(text, regex) {
    if (this._debug) {
      console.log("MyRegExp::exec");
    }
  };

  return MyRegExp;

})();

//# sourceMappingURL=MyRegExp.js.map
