// Generated by CoffeeScript 1.10.0
var i, j, len, len1, myRegExp, regex, regexs;

regexs = ['(abc)', '[0-9]+', '[0-9+', '[yY]ves', '[yYves', '[0-9]{2}-[0-9]{2}-[0-9]{4}', '[0-9]{1,}', '[0-9]{,1}', '[0-9]{}', '[0-9]{', 'Je m\'appelle (\w)'];

myRegExp = new MyRegExp();

len = regexs.length - 1;

for (i = j = 0, len1 = regexs.length; j < len1; i = ++j) {
  regex = regexs[i];
  console.log("[" + i + "/" + len + "] " + regex + " : " + (myRegExp.isValid(regex)));
}

//# sourceMappingURL=testMyRegExp.js.map
